# PPO RL config
ppo:
  rollout_length: 128
  num_envs: 16
  epochs: 4
  minibatch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  lr: 3e-4
network:
  hidden_sizes: [256, 256]
  recurrent: true
# [AUDITED] rl.ppo.yaml reviewed for realistic hyperparams
